#!/usr/bin/env zsh

successfully() {
  $* || (echo "\nfailed" 1>&2 && exit 1)
}

fancy_echo() {
  echo "\n$1"
}

if [ -f /etc/zshenv ]; then
  fancy_echo "Fix OSX zsh environment bug ..."
    successfully sudo mv /etc/{zshenv,zshrc}
fi

fancy_echo "Install Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

fancy_echo "Install Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8

fancy_echo "Install Redis, a good key-value database ..."
  successfully brew install redis

fancy_echo "Install The Silver Searcher (better than ack or grep) for searching the contents of files ..."
  successfully brew install the_silver_searcher

fancy_echo "Install ImageMagick, for cropping and re-sizing images ..."
  successfully brew install imagemagick

fancy_echo "Install QT, used by Capybara Webkit for headless Javascript integration testing ..."
  successfully brew install qt

fancy_echo "Install watch, used to execute a program periodically and show the output ..."
  successfully brew install watch

fancy_echo "Installing autojump, for a faster way to navigate your filesystem ..."
  successfully brew install autojump

fancy_echo "Install rbenv for changing Ruby versions ..."
  successfully brew install rbenv

fancy_echo "Enable shims and autocompletion ..."
      successfully eval "$(rbenv init -)"

fancy_echo "Install rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
  successfully brew install rbenv-gem-rehash

fancy_echo "Install ruby-build for installing Rubies ..."
  successfully brew install ruby-build

fancy_echo "Install GNU Compiler Collection, a necessary prerequisite to installing Ruby ..."
  successfully brew tap homebrew/dupes
  successfully brew install apple-gcc42

fancy_echo "Install Ruby 1.9.3-p448 ..."
  CC=gcc-4.2 successfully rbenv install 1.9.3-p448

fancy_echo "Set Ruby 1.9.3-p448 as global default Ruby ..."
  successfully rbenv global 1.9.3-p448
  successfully rbenv shell 1.9.3-p448

fancy_echo "Update to latest Rubygems version ..."
  successfully gem update --system

fancy_echo "Install critical Ruby gems for Rails development ..."
  successfully gem install bundler foreman pg rails thin --no-document

fancy_echo "Install GitHub CLI client ..."
  successfully gem install hub --no-document

fancy_echo "Install Heroku CLI client ..."
  successfully brew install heroku-toolbelt

fancy_echo "Almost done. Right now install fs/dotfiles."
